### PR TITLE
Update nested dictionnaries in cascaded configs

### PR DESCRIPTION
**Pull request by afraisse**
Instead of overwriting nested configs, check if the config item is a dict and if so, update it instead.

This allows generic definitions of nested dictionaries, such as parameters or scepte_user_data for instance.
See the updated test for example.
Really enjoying sceptre here at ubisoft, thanks for sharing!

### CODE REVIEW

**Comment by afraisse** [comment]
Since I created this merge request, changes in the tests have made them to fail. I got no feedback on this PR, but saw that you're deprecating cascading stack config. Should this PR be discarded then ?

**Comment by theseanything** [comment]
Apologies @afraisse! Yes we are deprecating cascading config. I agree we need for shared/common values - however we think cascading config doesn't provide a flexible enough solution. For example config can only be cascaded down into a single file within an environment (due to the file name needing to be same). We currently have support for variables file - which is a partial solution this solution. Further discussion on this problem is needed.

**Comment by afraisse** [comment]
@theseanything Thanks for the feedback !

**Comment by JuanCanham** [comment]
Can we re-look at this for v1, variable files still seam ugly and this still seams like a much cleaner fix when cascading configs are supported (v1)

**Pull request closed without merging**
