### PR TITLE
[Resolve #310] Pass `profile` key to ConnectionManager

### LINKED ISSUE #310: `profile` config key is not passed to ConnectionManager
Hi there! I was just working through my first basic Sceptre project (similar to the one [here](https://sceptre.cloudreach.com/latest/docs/get_started.html)) and I was trying a basic config file that uses the `profile` parameter to specify credentials from `~/.aws/credentials`. I ran into some issues (see below).

Here's my config.yaml:

```yaml
project_code: sample-app
region: us-east-1
profile: personal                             
template_bucket_name: lars-sample-app-conflict  # I was playing around to see if I could reproduce https://github.com/cloudreach/sceptre/issues/303
```

From what I understand of the docs, this _should_ be a valid

Before launching anything, I tried to run `sceptre status dev`. Here's what happened:

```
$ sceptre status dev
Traceback (most recent call last):
  File "/Users/larsbutler/.virtualenvs/sceptre/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre', 'console_scripts', 'sceptre')()
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/larsbutler/.virtualenvs/sceptre/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/cli/helpers.py", line 39, in decorated
    return func(*args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/cli/status.py", line 25, in status_command
    write(env.describe(), output_format=output_format, no_colour=no_colour)
  File "/Users/larsbutler/proj/sceptre/sceptre/helpers.py", line 61, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/environment.py", line 104, in describe
    status = stack.get_status()
  File "/Users/larsbutler/proj/sceptre/sceptre/stack.py", line 569, in get_status
    status = self.describe()["Stacks"][0]["StackStatus"]
  File "/Users/larsbutler/proj/sceptre/sceptre/stack.py", line 328, in describe
    kwargs={"StackName": self.external_name}
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 227, in call
    client = self._get_client(service)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 195, in _get_client
    self.clients[service] = self.boto_session.client(service)
  File "/Users/larsbutler/proj/sceptre/sceptre/connection_manager.py", line 160, in boto_session
    self._boto_session.get_credentials().method,
AttributeError: 'NoneType' object has no attribute 'method'
```

The error is a bit obscure and doesn't actually tell much about the real issue, but fortunately after a quick debugging session, I found out that the `profile` is not being passed to the ConnectionManager constructor. It's a fairly simple fix. Pull request coming shortly! :)

Note: A similar error happens with `sceptre launch ...`, and probably other commands.

### PR DESCRIPTION
**Pull request by larsbutler**
This is fairly simple change that fixes #310: Pass the `profile` key from the config.yaml to `sceptre.stack.Stack` and subsequently to `sceptre.connection_manager.ConnectionManager` constructors.

The existing tests needed to be tweaked slightly. Let me know if you'd like to see more tests for this and/or if you'd like these commits squashed together.

---
- [x] Wrote good commit messages.
- [ ] Squashed related commits together after the changes have been approved.
- [x] Commit message starts with [Resolve #issue-number] (if a related issue exists).
- [ ] Added unit tests.
- [ ] Added integration tests (if applicable).
- [x] All unit tests (make test) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code doesn't generate flake8 (make lint) offenses.
- [x] The PR relates to only one subject with a clear title and description in grammatically correct, complete sentences.

### CODE REVIEW

**Comment by larsbutler** [comment]
@ngfgrant Okay, I'll resubmit this to a different target branch, then. Closing.

**Comment by larsbutler** [comment]
Well, according to #310 this is resolved now. This patch isn't needed.

**Comment by ngfgrant** [comment]
@larsbutler how were you able to merge this?

**Comment by larsbutler** [comment]
@ngfgrant I rebased it on v1, but the target was still master so the delta was huge. I switched my branch to be based on v1 (minus my changes) and pushed that to my branch--but with no delta from v1 to v1, github just counted it as a merge. Rather strange. :)

**Comment by ngfgrant** [comment]
Ah ok - the patch is still required. I wonder if it is possible to create a new branch from V1 branch (git checkout -b your-branch-name v1) and apply the patch there. then maybe open a new pull request from that branch? I will be able to merge straight into v1 from there.

**Comment by larsbutler** [comment]
@ngfgrant I can try, but the ConfgReader class has changed a lot and I'd need to take some time to figure out how to re-apply the change.

**Comment by ngfgrant** [comment]
ok let me check I can't remember V1 changing config reader much - but it is almost unrecognisable in v2. Also just to be clear is the issue you are having based on a tagged commit (e.g. an official version) or are you having issues based off of master?

**Pull request closed without merging**
