### PR TITLE
Added support for CloudFormation Macros by adding CAPABILITY_AUTO_EXPAND

### PR DESCRIPTION
**Pull request by adv4000**
CloudFormation Macros require Capability called CAPABILITY_AUTO_EXPAND.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [ ] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by ngfgrant** [comment]
Hi @adv4000 

Thanks for the PR! Could you please add some unit and integration tests around this?

Thanks,
Niall

**Comment by adv4000** [comment]
> Hi @adv4000
> 
> Thanks for the PR! Could you please add some unit and integration tests around this?
> 
> Thanks,
> Niall

I'am not a programmer, don't know how to do it.
This is how I fixed it on my Sceptre 1.4 installation, just by adding additional Capability name into file **stack.py**

**Comment by m1keil** [comment]
@ngfgrant I think you should consider making capabilities a property of stack config:

1. It's likely that there will be future capabilities added to CF
2. It's probably not the best idea to run with every stack with all capabilities ON by default

Your thoughts?

**Comment by ngfgrant** [comment]
@m1keil agreed that it would be a good idea to think about this in more detail. For v2 I think we will be more specific but for v1 it probably matters a bit less.

**Comment by ngfgrant** [comment]
Closing as won't support in v1. v1 EOL as of tomorrow.

**Pull request closed without merging**
