### PR TITLE
[Resolve #312] add badges

### LINKED ISSUE #312: improving the Readme file with Badges
most of the public repository has badge with the current pypi version inside the readme and the "building" process

could be nice to have also in sceptre

### PR DESCRIPTION
**Pull request by giuliocalzolari**
pypi and target of CircleCI
-----------------

* [x] Wrote [good commit messages][1].
* [x] [Squashed related commits together][2] after the changes have been approved.
* [x] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [x] Added unit tests.
* [x] Added integration tests (if applicable).
* [x] All unit tests (`make test`) are passing.
* [x] Used the same coding conventions as the rest of the project.
* [x] The new code doesn't generate flake8 (`make lint`) offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by giuliocalzolari** [comment]
Hi @ngfgrant this is a simple improvements of the current Readme, there isn't any real issue connected but is just to make our repository a little bit more friendly

**Comment by niallgrantcloudreach** [comment]
Hey Giulio it’s not entirely clear what the improvements are and why they need to be made. Issue doesn’t need to be long but it does need to exist. Cheers N

**Comment by giuliocalzolari** [comment]
@niallgrantcloudreach done

**Comment by giuliocalzolari** [comment]
@seanrankine already done

**Pull request merged**
