### PR TITLE
[Resolves #324] Add CAPABILITY_AUTO_EXPAND permission to enable transforms for SAM templates

### LINKED ISSUE #324: Support for AWS SAM templates
Would be great for native support of AWS SAM Templates using the Transform attribute.

This requires Sceptre:
 - Create a stack via change set
 - Package and deploy lambda code to S3

### PR DESCRIPTION
**Pull request by kkessels**
CloudFormation requires the CAPABILITY_AUTO_EXPAND permission in order to execute the SAM template transform (see issue #538 and #324). This PR adds this permission to the create stack, update stack, and create change set plan actions.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [x] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by ngfgrant** [comment]
Hey @kkessels 

Thanks so much for the PR. First pass looks good. Would you be able to add some integration test scenarios/features  in `integration-tests/features/...`? I.e. a scenario in create-stack.feature could be `Scenario: create new stack that uses SAM template` or something similar. This might need to be done across create/update/launch etc.

Nice work!
Niall

**Comment by networkpadawan** [comment]
would it be possible to add this to v1?

**Comment by kkessels** [comment]
@networkpadawan The added IAM capabilities could probably be added to v1, though I have not looked at that code base at all. However, since we need change sets in order to use transforms, and to my knowledge v1 does not use change sets to deploy, this added IAM capability will not add any value. But please correct me if I am wrong

**Comment by kkessels** [comment]
@ngfgrant I added integrations tests for the create-stack, create-change-set, and update-stack features as these are the ones that seemed most relevant to me (this capability is not needed for deletes or the execution of a change set). The SAM templates for these tests create a minimal serverless function since a transform on a template where nothing needs to be transformed produced an error when deploying. I would be very surprised if this change breaks something since all it is doing is adding an extra explicit acknowledgment during deployment and not actually adding any logic, etc. but let me know if something is still missing.

**Comment by adv4000** [comment]
> would it be possible to add this to v1?

https://github.com/cloudreach/sceptre/pull/589

**Comment by ngfgrant** [comment]
@kkessels Looks good - I am will manually test at some point this week and will get this out in the next release.

**Comment by kkessels** [comment]
@ngfgrant Great! It will be awesome to be able to use Sceptre for projects that include serverless components.

**Comment by zaro0508** [comment]
@ngfgrant wondering about the status of this?  I've been using for a while now and seems to be working great.  Any change it can get merged?

**Comment by ngfgrant** [comment]
Yeh I am good with this. Waiting on getting a couple additional things across the project board and this will be out in the next release. Scheduled for 14th Feb.

**Comment by pc-mreeves** [comment]
@kkessels re: the value of backporting this...
This is required to be able to use includes.
https://thomasvachon.com/articles/making-modular-cloudformation-with-includes/

So a CF template like this fails:
```
Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://some-dummy-bucket/shared/cf/mappings/account_map_basic.yaml
```

**Pull request merged**
