### PR TITLE
#264: 'import-stack' from AWS

### PR DESCRIPTION
**Pull request by oazmon**
This feature implements import-stack that import a single AWS CloudFormation stack from AWS into an existing sceptre environment.

* [V] Wrote [good commit messages][1].
* [V] [Squashed related commits together][2] after the changes have been approved.
* [V] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [V] Added unit tests.
* [ ]  Added integration tests (if applicable).
* [V] All unit tests (`make test`) are passing.
* [V] Used the same coding conventions as the rest of the project.
* [V] The new code doesn't generate flake8 (`make lint`) offenses.
* [V] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by oazmon** [comment]
I am writing the integration tests and proposed doc changes. Wanted to have early feed back. 
Also, once this is fully accepted, will write and submit a import-env that imports a set of stacks from AWS into sceptre

**Comment by ngfgrant** [comment]
@oazmon Thanks so much for the PR!

Can I just check something quickly? It looks like there is some duplication between the commits you made in this PR and the commits you made in #221. 

Could you just double check that the commits here are correct? I will look at your PR #221 today.

**Comment by oazmon** [comment]
I thought I reset the repo before I started coding this one. Apparently not. Will fix and resubmit. I just need a general review of am I in the right direction, following the product core teams philosophy for the product

**Comment by oazmon** [comment]
To get around mixed commits, had to create a new fork and PR

**Pull request closed without merging**
