### PR TITLE
Added hook to changesets

### PR DESCRIPTION
**Pull request by padilo**
This adds the possibility to add hooks points to changeset create and update operation, using this you can parametrize your template

```
hooks:
  before_create:
    - !my_hook "create param"
  before_update:
    - !my_hook "update param"
  before_create_change_set:
    - !my_hook "create_change_set param"
  before_update_change_set:
    - !my_hook "create_change_set param"
```

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] [Squashed related commits together][2] after the changes have been approved.
* [ ] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [ ] Added unit tests.
* [ ] Added integration tests (if applicable).
* [ ] All unit tests (`make test`) are passing.
* [x] Used the same coding conventions as the rest of the project.
* [x] The new code doesn't generate flake8 (`make lint`) offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by theseanything** [comment]
Hi @padilo, could you give me a example use cases for this functionality?

**Comment by padilo** [comment]
Sure.

Currently on our sceptre configuration we have a hook that populates a parameter with the AMI id. The hook basically builds the AMI, in case is not already build and populates a parameter of the sceptre config to be able to launch our cloudformation stack.

This works pretty well when launching or updating the stack, as sceptre has support to do it: `before_update`and `before_create`. But this hooks doesn't launch when you are creating a changeset. I was expecting that.

So to solve my issue I though the best way to do it and still being backward compatible is to have this two additional hooks `before_create_change_set` and `before_update_change_set`.

Here an exemple of our config:
```
stack_name: "zookeeper"
template_path: "cfn/zookeeper/zookeeper-cluster.json"

parameters:
  ClusterMaxSize: "5"
  ClusterMinSize: "2"
  ClusterDesiredSize: "3"

tags:
  Stack: zookeeper-cluster
hooks:
  before_create:
    - !packer "zookeeper ImageId"
  before_update:
    - !packer "zookeeper ImageId"
```

That will launch a packer called `zookeeper` (in case the image is not already build) and will populate `ImageId` as a parameter to launch the cloudformation stack.

This config doesn't work with changesets without this PR.

**Comment by theseanything** [comment]
@padilo Could you not use a resolver? 
e.g. 
```
parameters:
    ami_id: !packer "zookeeper ImageId"
```

**Comment by padilo** [comment]
Sounds very cool. I didn't know that can be done, I'll try it.

**Comment by padilo** [comment]
Thanks @theseanything worked very well for my usecase the use of custom resolvers.

I still think this hooks could be useful for others or at least to keep in mind that create and update hooks aren't launched on changesets.

**Comment by theseanything** [comment]
Awesome! I'm going to decline this PR for now - I'd like to open an issue to discuss this more.

**Comment by connorwilliamscr** [comment]
For SAM stacks, you can only update with update-stack-cs, but there are no hooks that yet exist for this command. This would be super useful for writing a custom hook for running the aws cloudformation package command which needs to be run every time the Lambda code is updated and needs to be re-deployed.

If you try to use update-stack, the following error occurs: An error occurred (ValidationError) when calling the UpdateStack operation: UpdateStack cannot be used with templates containing Transforms.

**Pull request closed without merging**
