### PR TITLE
#264 Feature/import stack oazmon

### PR DESCRIPTION
**Pull request by oazmon**
**Replace the text above the line with a summary of the changes in your PR.
The more detailed you are, the better. Before submitting the PR, make sure the following are checked.**

-----------------

* [x] Wrote [good commit messages][1].
* [x] [Squashed related commits together][2] after the changes have been approved.
* [x] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [x] Added unit tests.
* [x] Added integration tests (if applicable).
* [x] All unit tests (`make test`) are passing.
* [ ] Used the same coding conventions as the rest of the project.
* [x] The new code doesn't generate flake8 (`make lint`) offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by theseanything** [comment]
Hi @oazmon, we appreciate all the hard work gone into this PR, but I feel feature is not core to Sceptre at the moment. Although this functionality could be useful - due to limited to resources and the added maintenance burden - I am reluctant to merge this PR for now. However, this work would be suitable for a separate tool/python package or a Sceptre plugin (if we were to implement a plugin system).

**Comment by b-t-g** [comment]
Closing per @theseanything's comments.

**Comment by oazmon** [comment]
Hello @theseanything and @b-t-g,
I am a lead App Ops engineer at intuit Small Business. I have recommended and this tool is being adopted company wide. Hundreds of engineers world wide. I appreciate that a tool owners you have your philosophy and direction. However, I need a better communication line with you guys, so that I can better commit resources. I really don't want to produce a fork.
Now, that was the reason for issue #264 before I committed resources. 
I cannot wait months and months for a new feature, such as the above. We have tons of existing project in various home made and other tools and need to migrate. 
There are two things that are urgent for us at this time, and I want to achieve alignment before divergence:
1. A Migration tool. Creating a separate tool requires replicating all your great core code to do the import. I am not sure this is a good idea, but if I have no choice will do so.
2. An fetch template tool. In the current version of Sceptre we have use two template directories: templates, and shared-templates. For shared templates we place imported templates and in templates, project specific templates. The fetch is currently semi-manual. The next tool we are about to write is the fetch. Again, I would like this to be done in coordination with the core team, but I also have dead lines.
Please let's find a better channel to communicate to iron out these issues, so that we can proceed in alignment.

**Comment by oazmon** [comment]
P.S. My intuit e-mail is omer_azmon@intuit.com. My public github account uses my personal e-mail

**Pull request closed without merging**
