### PR TITLE
Auto use change sets when needed

### PR DESCRIPTION
**Pull request by JuanCanham**
Use change sets if the template requires it
* Add template_summary property to templates
* Add requires_change_sets property to templates
* Add launch_with_change_set function to stacks
* Change behaviour of Create/Update stacks to launch_with_change_set when requires_change_set property of it's template is true

By implementing this transparently at the stack level, this supports launch as well as create/update env commands

-----------------

* [x] Wrote [good commit messages][1].
* [x] [Squashed related commits together][2] after the changes have been approved.
* [x] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [x] Added unit tests.
* [x] Added integration tests (if applicable).
* [x] All unit tests (`make test`) are passing.
* [x] Used the same coding conventions as the rest of the project.
* [x] The new code doesn't generate flake8 (`make lint`) offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by jakul** [comment]
@JuanCanham This PR is (mostly) working for me, it allows me to use the `launch` command (which https://github.com/cloudreach/sceptre/pull/240 doesn't).

I've found a bug though - when running the `launch` command any stacks which don't have any updates fail, because when AWS tries to apply a change set with no changes it in it it fails.
```
[2018-03-07 11:17:06] - sceptre.environment - Stack trantor/construct-message-lambda failed to launch
Traceback (most recent call last):
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/environment.py", line 194, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/stack.py", line 243, in launch
    status = self.update()
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/hooks/__init__.py", line 103, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/stack.py", line 184, in update
    return self.launch_using_change_set()
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/stack.py", line 322, in launch_using_change_set
    return self.execute_change_set(change_set_name)
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/stack.py", line 571, in execute_change_set
    "StackName": self.external_name
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/connection_manager.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/src/sceptre/sceptre/connection_manager.py", line 228, in call
    return getattr(client, command)(**kwargs)
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/craig/.virtualenvs/trantor-qMKNBx-i/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeSetStatusException: An error occurred (InvalidChangeSetStatus) when calling the ExecuteChangeSet
```
image

**Comment by ngfgrant** [comment]
@JuanCanham is this something you'd want included in V1?

**Comment by JuanCanham** [comment]
I would, but I think I need to fix the bug in it @jakul mentioned.

**Comment by JuanCanham** [comment]
I believe i've fixed the bug raised by @jakul, sorry about the delay

**Comment by jakul** [comment]
I can confirm that this fixes the problem I was seeing. Thanks @JuanCanham

**Comment by jakul** [comment]
Not to self: This code is not part of the v2 codebase. https://github.com/cloudreach/sceptre/pull/586 might add the capability to use AWS SAM in deploy templates.

**Pull request merged**
