### PR TITLE
Fix CI interaction with moto 1.3.7

### PR DESCRIPTION
**Pull request by devenney**
**This PR targets a feature branch - not master! See #654.**

* Works around https://github.com/spulec/moto/issues/1924 by ensuring garbage defaults are set in the environment.

Signed-off-by: Brendan Devenney <brendan@devenney.io>

Resolves CI issues introduced by bumping the `moto` version. In short, moto currently cannot handle a lack of a default profile (or default access keys in the environment). See: https://github.com/spulec/moto/issues/1924. This appears to be fixed upstream by https://github.com/spulec/moto/pull/1952 but has not been cut for release.

Also handles the exception thrown in a more user-friendly way as this has popped previously (#310) under different circumstances.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [x] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by devenney** [comment]
@ngfgrant I've pushed changes to the Dockerfile to support Python 3.7 alongside 3.6. Seems quite a nifty solution and tox seems happy inside the container locally. If you're happy with it, I think the image update is one for you to do?

**Comment by ngfgrant** [comment]
Hey @devenney thanks for the PR - circle seems to be complaining about Interpreter not found https://circleci.com/gh/cloudreach/sceptre/3509?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link :(

**Comment by devenney** [comment]
I think that's a good call. My only concern is that we won't be able to get a passing build on either PR until one has been force merged. As long as we're aware of that it's all good. Will split them out once I get some breathing room. 👍

**Comment by devenney** [comment]
@ngfgrant I've pulled the connection manager changes out of this (other than the moto 1.3.7 workaround in the tests). Should be good to build the Docker image and see if it goes green.

**Pull request merged**
