### PR TITLE
Adding support for S3 in china region

### PR DESCRIPTION
**Pull request by jfgiroux**
Since S3 in China is not using the same url as the other regions, I added a check to verify if the region specified is China, if yes, a specific url is returned for S3. I didn't do any integration tests because you need a different account to access the China region.

-----------------

* [x] Wrote [good commit messages][1].
* [ ] [Squashed related commits together][2] after the changes have been approved.
* [x] Commit message starts with `[Resolve #issue-number]` (if a related issue exists).
* [x] Added unit tests.
* [ ] Added integration tests (if applicable).
* [x] All unit tests (`make test`) are passing.
* [x] Used the same coding conventions as the rest of the project.
* [x] The new code doesn't generate flake8 (`make lint`) offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by jfgiroux** [comment]
Hi,

Do you have and ETA when this could be merge?

Thanks!

**Comment by ngfgrant** [comment]
Which version are you hoping to use this in? Currently, looks like the PR is for v2? If that is the case then I will try get it in for v2 release this week.

**Comment by jfgiroux** [comment]
Well I guess it depends what will be the next release. Are you planning to release a v1.4.1 or the next release will be v2.0.0?

We are going to production with that code around october I would say

**Comment by ngfgrant** [comment]
The changes that are made are to v2 files so for this PR at least would need to wait for 2.0 which I am aiming to get out this week. There will probably also be a 1.4.1 this week too given a recent bug that was raised. In any case v2 will defnintiely be out well before October.

**Comment by jfgiroux** [comment]
all good for v2 then! 
Thanks a lot

**Pull request closed without merging**
